name: example-basic-pnpm
on:
  branch_protection_rule:
    types: [created, deleted]
jobs:
  basic-pnpm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('examples/basic-pnpm/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Download the build folder
        uses: actions/download-artifact@v4
        with:
          name: build
          path: build
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true
          browser: chrome
